[package]
name = "fiox"
version = "0.2.0"
edition = "2024"
[workspace.metadata.clippy]
deny-warnings = true
[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = "1.0.228"
serde_json = "1.0.145"
toml = "0.9.8"
csv = "1.4.0"
resext = "0.6.0"
